pragma Singleton
import QtQuick

// Лёгкий i18n-синглтон. T.s("key") -> локализованная строка по текущему T.lang ("ru" | "en").
// Реактивно: text bindings, ссылающиеся на T.s(...), переоценятся при смене lang.
// Неизвестный ключ → возвращается сам ключ (видно в UI и удобно для поиска недопереводов).
QtObject {
    property string lang: "ru"
    readonly property var langs: ["ru", "en"]

    function s(key) {
        var d = dict[lang] || dict.ru
        return d[key] !== undefined ? d[key] : key
    }

    readonly property var dict: ({
        ru: {
            // ── sidebar / навигация ──
            "nav.dashboard": "Главная",
            "nav.locations": "Серверы",
            "nav.routing":   "Маршрутизация",
            "nav.settings":  "Настройки",
            "nav.account":   "Аккаунт",
            "page.locations": "Локации",
            "page.settings":  "Настройки",
            "page.routing":   "Маршрутизация",

            // ── ModeSwitch / статусы ──
            "mode.proxy": "Прокси",
            "mode.tun":   "TUN",
            "status.connected":    "Подключено",
            "status.connecting":   "Подключение…",
            "status.disconnected": "Не подключено",
            "statusbar.active":    "Активно",
            "statusbar.connecting":"Соединение…",
            "statusbar.offline":   "Не в сети",
            "ring.protected":      "ЗАЩИЩЕНО",
            "ring.connecting":     "ПОДКЛЮЧЕНИЕ",
            "ring.disconnected":   "ОТКЛЮЧЕНО",

            // ── общие кнопки ──
            "btn.connect":    "Подключить",
            "btn.disconnect": "Отключить",
            "btn.connecting": "Подключение…",
            "btn.cancel":     "Отмена",
            "btn.save":       "Сохранить",
            "btn.import_conf": "Импорт .conf",
            "btn.delete":     "Удалить",
            "btn.edit":       "Изменить",
            "btn.add":        "Добавить",
            "btn.create":     "Создать",
            "btn.open":       "Открыть",
            "btn.close":      "Закрыть",
            "btn.copy":       "Копировать",
            "btn.copylink":   "Копировать ссылку",
            "btn.clear":      "Очистить",
            "btn.import":     "Импорт из буфера",
            "btn.share":      "Поделиться",
            "btn.ping":       "Пинг",
            "btn.measure":    "Замерить",
            "drop.dropfile":  "Бросьте файл для импорта",
            "drop.formats":   "WireGuard .conf · текст с vless:// vmess:// trojan:// ss://",
            "wiz.welcome":      "Добро пожаловать в Kitsune",
            "wiz.langhint":     "Выберите язык интерфейса. Поменять можно в любое время в Настройках.",
            "wiz.next":         "Далее",
            "wiz.back":         "Назад",
            "wiz.skip":         "Пропустить",
            "wiz.subtitle":     "Добавьте свою VPN-подписку",
            "wiz.subhint":      "Вставьте URL подписки (https://…) или сразу ссылки vless:// vmess:// trojan:// ss://",
            "wiz.subplaceholder": "https://… или vless://…",
            "wiz.subdefname":   "Моя подписка",
            "wiz.add":          "Добавить",
            "wiz.donetitle":    "Всё готово!",
            "wiz.donehint":     "Откроется главный экран. Жмите большую кнопку — Kitsune подключит вас к лучшему серверу.",
            "wiz.golet":        "Поехали",
            "btn.best":       "Лучший",
            "btn.paste":      "Вставить",
            "btn.fromclip":   "Из буфера",
            "btn.duplicate":  "Дублировать",
            "btn.connectto":  "Подключиться",
            "btn.check":      "Проверить",
            "btn.reset":      "Сбросить",
            "btn.rescan":     "Пересканировать",
            "btn.page":       "Страница",
            "btn.importrules":"Импорт",
            "btn.doimport":   "Импортировать",
            "btn.rule":       "Правило",
            "btn.server":     "Сервер",
            "btn.subscription":"Подписка",
            "btn.auto":       "Авто",
            "btn.manual":     "Вручную",

            // ── секции Settings ──
            "sec.language":      "ЯЗЫК",
            "sec.interface":     "ИНТЕРФЕЙС",
            "sec.app":           "ПРИЛОЖЕНИЕ",
            "sec.community":     "СООБЩЕСТВО",
            "set.tg":            "Telegram-канал",
            "set.tg.sub":        "Анонсы релизов и хотфиксов · @KitsuneConnect",
            "set.github":        "Исходный код",
            "set.github.sub":    "Репозиторий на GitHub · MIT-лицензия",
            "btn.open":          "Открыть",
            "sec.core":          "ЯДРО",
            "sec.subscription":  "ПОДПИСКА",
            "sec.connection":    "ПОДКЛЮЧЕНИЕ",
            "sec.hotkey":        "ГОРЯЧАЯ КЛАВИША",
            "sec.security":      "БЕЗОПАСНОСТЬ",
            "sec.inbound":       "ВХОДЯЩЕЕ СОЕДИНЕНИЕ",
            "sec.tun":           "РЕЖИМ TUN",
            "sec.dns":           "DNS",
            "sec.mux":           "МУЛЬТИПЛЕКСИРОВАНИЕ",
            "sec.diagnostics":   "ДИАГНОСТИКА",

            // ── секции Routing ──
            "rt.profiles":         "ПРОФИЛИ",
            "rt.profilefinal":     "ПРОФИЛЬ И ФИНАЛЬНОЕ ДЕЙСТВИЕ",
            "rt.presets":          "ПРЕСЕТЫ",
            "rt.rules":            "ПРАВИЛА",
            "rt.apps":             "ПРИЛОЖЕНИЯ",

            // ── SettingRow / тумблеры ──
            "set.theme":           "Тёмная тема",
            "set.theme.sub":       "Светлое / тёмное оформление",
            "set.tray":            "Сворачивать в трей",
            "set.tray.sub":        "Прятать окно вместо закрытия",
            "set.autoconf":        "Подстраивать под подписку",
            "set.autoconf.sub":    "Применять маршрутизацию / DNS / параметры из подписки",
            "set.subautoref":      "Авто-обновление подписок",
            "set.subautoref.sub":  "Обновлять подписки с включённым «Авто» в фоне — на старте и по интервалу",
            "loc.subauto":         "Авто",
            "loc.subauto.tt":      "Интервал задан самим сервером подписки (Profile-Update-Interval)",
            "misc.shorth":         " ч",
            "set.subinterval":     "Интервал обновления",
            "set.subinterval.sub": "Как часто перепроверять",
            "interval.3h":         "3 ч",
            "interval.6h":         "6 ч",
            "interval.12h":        "12 ч",
            "interval.24h":        "24 ч",
            "set.autostart":       "Автозапуск с системой",
            "set.autostart.sub":   "Запускать при входе в Windows",
            "set.autoconnect":     "Автоподключение",
            "set.autoconnect.sub": "Подключаться сразу при запуске",
            "set.connectto":       "Подключать к",
            "set.connectto.sub":   "Последнему выбранному или быстрейшему по пингу",
            "set.reconnect":       "Авто-реконнект",
            "set.reconnect.sub":   "Восстанавливать соединение при разрыве (до 5 попыток)",
            "set.failover":        "Авто-переключение между серверами",
            "set.failover.sub":    "Sing-box urltest: тестит сервера каждые 3 минуты, переключается на самый быстрый. Ручной выбор сервера отключён.",
            "set.hotkey":          "Глобальный хоткей",
            "set.hotkey.sub":      "Вкл/выкл VPN даже когда окно свёрнуто",
            "set.combo":           "Комбинация",
            "set.combo.sub":       "Модификатор + буква/цифра",
            "set.killswitch":      "Kill-switch",
            "set.killswitch.sub":  "Резать интернет при разрыве туннеля (требует прав администратора)",
            "set.port":            "Локальный порт (mixed)",
            "set.port.sub":        "SOCKS + HTTP на одном порту",
            "set.lan":             "Разрешить из LAN",
            "set.lan.sub":         "Принимать подключения из локальной сети",
            "set.tunmode":         "Режим TUN",
            "set.tunmode.sub":     "Системный туннель (нужны права админа)",
            "set.tunstack":        "Сетевой стек",
            "set.strict":          "Strict route",
            "set.strict.sub":      "Жёсткий захват (может ломать DNS — вкл. только при утечках)",
            "set.dnsremote":       "Удалённый DNS",
            "set.dnsremote.sub":   "Резолвинг через прокси",
            "set.dnsdirect":       "Прямой DNS",
            "set.dnsdirect.sub":   "Для обходов / локальных доменов",
            "set.sniff":           "Sniffing",
            "set.sniff.sub":       "Определять домен для маршрутизации",
            "set.fakeip":          "Fake-IP",
            "set.fakeip.sub":      "Ускоряет резолвинг, меньше утечек",
            "set.mux":             "Включить Mux",
            "set.mux.sub":         "Несколько потоков в одном соединении",
            "set.muxproto":        "Протокол",
            "set.routeprofile":    "Профиль маршрута",
            "set.routefinal":      "Финальный outbound",
            "set.routefinal.sub":  "Куда идёт трафик, не попавший в правила",
            "set.routelan":        "Обход локальной сети",
            "set.routelan.sub":    "LAN и приватные подсети — напрямую",
            "set.routeru":         "Прямой доступ к RU-сайтам",
            "set.routeru.sub":     "geosite:ru / geoip:ru мимо прокси",
            "set.adblock":         "Блокировка рекламы",
            "set.adblock.sub":     "Резать рекламные и трекерные домены",
            "set.proxyall":        "Проксировать всё",
            "set.proxyall.sub":    "Игнорировать обходы (кроме LAN)",
            "set.checkup":         "Проверка обновлений",
            "set.checkup.sub":     "Запрос к GitHub-релизам sing-box · авто-проверка на старте",
            "set.autoupdate":      "Авто-обновление",

            // ── язык ──
            "label.lang":          "Язык интерфейса",

            // ── диагностика / логи ──
            "logs.title":   "Логи ядра",
            "logs.sub":     "Для диагностики · по умолчанию скрыты",
            "logs.footer":  "Открывается только отсюда — в основном UI скрыто",
            "logs.filter":  "Поиск по логу…",
            "logs.found":   "Найдено строк:",

            // ── модалки: новый профиль ──
            "modal.profile.title":  "Новый профиль",
            "modal.profile.hint":   "Будет создан как копия текущих настроек маршрутизации и правил. После создания можно править — изменения сохраняются автоматически.",
            "modal.profile.ph":     "напр. Игровой / Только Discord / Стрим",

            // ── модалки: новая подписка ──
            "modal.sub.title":      "Новая подписка",
            "modal.sub.url":        "ССЫЛКА ПОДПИСКИ",
            "modal.sub.urlph":      "https://…  или  vless:// / vmess://",
            "modal.sub.name":       "НАЗВАНИЕ",
            "modal.sub.nameph":     "напр. My VPN",

            // ── модалки: новое правило ──
            "modal.rule.title":     "Новое правило",
            "modal.rule.type":      "ТИП",
            "modal.rule.value":     "ЗНАЧЕНИЕ",
            "modal.rule.action":    "ДЕЙСТВИЕ",
            "modal.rule.ph":        "напр. *.example.com  /  RU  /  app.exe",

            // ── модалки: импорт правил ──
            "modal.imp.title":      "Импорт правил",
            "modal.imp.hint":       "Вставь конфиг или массив правил. Авто-определит формат:\n• sing-box JSON (полный конфиг, объект с route.rules, или массив правил)\n• Clash / clash.meta YAML (секция rules:)",

            // ── модалки: редактор сервера ──
            "modal.srv.titlenew":   "Новый сервер",
            "modal.srv.title":      "Сервер",
            "modal.srv.name":       "ИМЯ / МЕТКА",
            "modal.srv.nameph":     "напр. Netherlands #1",
            "modal.srv.proto":      "ПРОТОКОЛ",
            "modal.srv.addrport":   "АДРЕС И ПОРТ",
            "modal.srv.uuidph":     "xxxxxxxx-xxxx-xxxx-…",
            "modal.srv.password":   "ПАРОЛЬ",
            "modal.srv.passwordph": "пароль",
            "modal.srv.method":     "МЕТОД ШИФРОВАНИЯ",
            "modal.srv.security":   "БЕЗОПАСНОСТЬ",
            "modal.srv.transport":  "ТРАНСПОРТ",
            "modal.srv.wgkey":      "ПРИВАТНЫЙ КЛЮЧ",
            "modal.srv.psk":        "PRE-SHARED KEY (опц.)",
            "modal.srv.pskph":      "base64 psk (если есть)",

            // ── модалки: share/QR ──
            "modal.share.title":    "Поделиться сервером",
            "modal.share.noqr":     "QR недоступен",

            // ── locations / poiск ──
            "loc.search":           "Поиск по серверам",
            "loc.empty":            "Здесь пока пусто",
            "loc.emptyhint":        "Вставьте ссылку из буфера или добавьте сервер вручную",
            "loc.updated":          "Обновлено: ",
            "loc.fromsub":          "Часть настроек берётся из подписки «",

            // ── приложения ──
            "apps.search":          "Поиск приложения…",
            "apps.scanning":        "Сканирую установленные приложения…",
            "apps.notfound":        "Ничего не найдено по запросу «",
            "apps.notfoundtail":    "»",

            // ── контекстное меню сервера ──
            "ctx.connect":          "Подключиться",
            "ctx.edit":             "Изменить",
            "ctx.duplicate":        "Дублировать",
            "ctx.copylink":         "Копировать ссылку",
            "ctx.share":            "Поделиться",
            "ctx.delete":           "Удалить",

            // ── разное ──
            "misc.profile.hint":    "Профиль = «слепок» всех настроек маршрутизации (LAN-обход, регион, реклама, финальное действие, правила). Любая правка сохраняется в активный профиль автоматически.",
            "misc.soon":            "скоро",
            "misc.demoerr":         "показать пример ошибки",

            // ── Segmented options / выпадающие списки ──
            "seg.auto":             "Авто",
            "seg.proxy":            "Прокси",
            "seg.direct":           "Прямо",
            "seg.block":            "Блок",
            "seg.vpn":              "VPN",
            "seg.last":             "Последний",
            "seg.fastest":          "Быстрейший",
            "seg.global":           "Global",
            "seg.ru":               "RU",
            "seg.manual":           "Вручную",

            // ── Locations пустое состояние / поиск ──
            "loc.searchph":         "Поиск по серверам",
            "loc.unsecured":        "Соединение не защищено",
            "loc.myip":             "Мой IP · ",
            "vrf.idle":             "Проверить",
            "vrf.checking":         "Проверяем…",
            "vrf.match":            "VPN активен",
            "vrf.mismatch":         "Другая страна",
            "vrf.off":              "VPN не работает",
            "vrf.error":            "Не удалось проверить",
            "loc.notfound":         "Ничего не найдено",
            "loc.notfoundq":        "По запросу «",
            "loc.notfoundtail":     "» ничего не найдено",
            "loc.fav.add":          "В избранное",
            "loc.fav.remove":       "Убрать из избранного",

            // ── Подписка / группы ──
            "sub.loading":          "Загрузка…",
            "sub.applied":          "Настройки применены из подписки «",
            "sub.notinstalled":     "не установлен",
            "sub.update":           "Обновить",
            "misc.available":       "доступно",

            // ── Apps section dynamic ──
            "apps.activeprofile":   "Активный профиль: «",
            "apps.defaultis":       "» (default: ",
            "apps.action.hint":     "Авто — действие по профилю. VPN — в туннель. Прямо — мимо туннеля.",

            // ── Confirm dialogs ──
            "confirm.delsub":       "Удалить подписку «",
            "confirm.delprof":      "Удалить профиль «",
            "confirm.delsrv":       "Удалить сервер «",
            "confirm.tail":         "»?",
            "confirm.delperapp":    "Снять ВСЕ per-app правила?",

            // ── Прочее ──
            "misc.bigfox":          "🦊 Режим Китсунэ включён",
            "misc.normalth":        "Обычная тема",
            "misc.standard":        "Стандартный",
            "misc.newsrv":          "Новый сервер",
            "misc.savebtn":         "Сохранить",
            "misc.addbtn":          "Добавить",
            "misc.langname.ru":     "Русский",
            "misc.langname.en":     "English",
            "misc.langnames":       "Русский / English",
            "misc.langnames.en":    "English / Русский",
            "units.mb":             " МБ",
            "units.gb":             " ГБ"
        },
        en: {
            "nav.dashboard": "Dashboard",
            "nav.locations": "Servers",
            "nav.routing":   "Routing",
            "nav.settings":  "Settings",
            "nav.account":   "Account",
            "page.locations": "Locations",
            "page.settings":  "Settings",
            "page.routing":   "Routing",

            "mode.proxy": "Proxy",
            "mode.tun":   "TUN",
            "status.connected":    "Connected",
            "status.connecting":   "Connecting…",
            "status.disconnected": "Disconnected",
            "statusbar.active":    "Active",
            "statusbar.connecting":"Connecting…",
            "statusbar.offline":   "Offline",
            "ring.protected":      "PROTECTED",
            "ring.connecting":     "CONNECTING",
            "ring.disconnected":   "DISCONNECTED",

            "btn.connect":    "Connect",
            "btn.disconnect": "Disconnect",
            "btn.connecting": "Connecting…",
            "btn.cancel":     "Cancel",
            "btn.save":       "Save",
            "btn.import_conf": "Import .conf",
            "btn.delete":     "Delete",
            "btn.edit":       "Edit",
            "btn.add":        "Add",
            "btn.create":     "Create",
            "btn.open":       "Open",
            "btn.close":      "Close",
            "btn.copy":       "Copy",
            "btn.copylink":   "Copy link",
            "btn.clear":      "Clear",
            "btn.import":     "Import from clipboard",
            "btn.share":      "Share",
            "btn.ping":       "Ping",
            "btn.measure":    "Measure",
            "drop.dropfile":  "Drop file to import",
            "drop.formats":   "WireGuard .conf · text with vless:// vmess:// trojan:// ss://",
            "wiz.welcome":      "Welcome to Kitsune",
            "wiz.langhint":     "Pick your language. You can switch it any time from Settings.",
            "wiz.next":         "Next",
            "wiz.back":         "Back",
            "wiz.skip":         "Skip",
            "wiz.subtitle":     "Add your VPN subscription",
            "wiz.subhint":      "Paste a subscription URL (https://…) or vless:// vmess:// trojan:// ss:// links directly",
            "wiz.subplaceholder": "https://… or vless://…",
            "wiz.subdefname":   "My subscription",
            "wiz.add":          "Add",
            "wiz.donetitle":    "All set!",
            "wiz.donehint":     "The main screen will open. Hit the big button — Kitsune picks the fastest server for you.",
            "wiz.golet":        "Let's go",
            "btn.best":       "Best",
            "btn.paste":      "Paste",
            "btn.fromclip":   "From clipboard",
            "btn.duplicate":  "Duplicate",
            "btn.connectto":  "Connect",
            "btn.check":      "Check",
            "btn.reset":      "Reset",
            "btn.rescan":     "Rescan",
            "btn.page":       "Page",
            "btn.importrules":"Import",
            "btn.doimport":   "Import",
            "btn.rule":       "Rule",
            "btn.server":     "Server",
            "btn.subscription":"Subscription",
            "btn.auto":       "Auto",
            "btn.manual":     "Manual",

            "sec.language":      "LANGUAGE",
            "sec.interface":     "INTERFACE",
            "sec.app":           "APP",
            "sec.community":     "COMMUNITY",
            "set.tg":            "Telegram channel",
            "set.tg.sub":        "Release announcements and hotfixes · @KitsuneConnect",
            "set.github":        "Source code",
            "set.github.sub":    "GitHub repository · MIT-licensed",
            "btn.open":          "Open",
            "sec.core":          "CORE",
            "sec.subscription":  "SUBSCRIPTION",
            "sec.connection":    "CONNECTION",
            "sec.hotkey":        "HOTKEY",
            "sec.security":      "SECURITY",
            "sec.inbound":       "INBOUND CONNECTION",
            "sec.tun":           "TUN MODE",
            "sec.dns":           "DNS",
            "sec.mux":           "MULTIPLEXING",
            "sec.diagnostics":   "DIAGNOSTICS",

            "rt.profiles":         "PROFILES",
            "rt.profilefinal":     "PROFILE & FINAL ACTION",
            "rt.presets":          "PRESETS",
            "rt.rules":            "RULES",
            "rt.apps":             "APPS",

            "set.theme":           "Dark theme",
            "set.theme.sub":       "Light / dark appearance",
            "set.tray":            "Minimize to tray",
            "set.tray.sub":        "Hide window instead of closing",
            "set.autoconf":        "Adapt to subscription",
            "set.autoconf.sub":    "Apply routing / DNS / params from subscription",
            "set.subautoref":      "Auto-refresh subscriptions",
            "set.subautoref.sub":  "Refresh subs with «Auto» enabled in the background — on startup and on interval",
            "loc.subauto":         "Auto",
            "loc.subauto.tt":      "Interval is dictated by the subscription server (Profile-Update-Interval)",
            "misc.shorth":         " h",
            "set.subinterval":     "Refresh interval",
            "set.subinterval.sub": "How often to recheck",
            "interval.3h":         "3 h",
            "interval.6h":         "6 h",
            "interval.12h":        "12 h",
            "interval.24h":        "24 h",
            "set.autostart":       "Start with system",
            "set.autostart.sub":   "Launch when logging into Windows",
            "set.autoconnect":     "Auto-connect",
            "set.autoconnect.sub": "Connect on app start",
            "set.connectto":       "Connect to",
            "set.connectto.sub":   "Last selected or fastest by ping",
            "set.reconnect":       "Auto-reconnect",
            "set.reconnect.sub":   "Restore connection on drop (up to 5 attempts)",
            "set.failover":        "Auto-failover between servers",
            "set.failover.sub":    "Sing-box urltest: probes every 3 minutes, switches to the fastest one. Manual server selection is disabled.",
            "set.hotkey":          "Global hotkey",
            "set.hotkey.sub":      "Toggle VPN even when window is hidden",
            "set.combo":           "Combination",
            "set.combo.sub":       "Modifier + letter/digit",
            "set.killswitch":      "Kill-switch",
            "set.killswitch.sub":  "Cut internet on tunnel drop (requires admin)",
            "set.port":            "Local port (mixed)",
            "set.port.sub":        "SOCKS + HTTP on the same port",
            "set.lan":             "Allow LAN access",
            "set.lan.sub":         "Accept connections from local network",
            "set.tunmode":         "TUN mode",
            "set.tunmode.sub":     "System tunnel (requires admin)",
            "set.tunstack":        "Network stack",
            "set.strict":          "Strict route",
            "set.strict.sub":      "Force capture (can break DNS — enable only on leaks)",
            "set.dnsremote":       "Remote DNS",
            "set.dnsremote.sub":   "Resolved via proxy",
            "set.dnsdirect":       "Direct DNS",
            "set.dnsdirect.sub":   "For bypasses / local domains",
            "set.sniff":           "Sniffing",
            "set.sniff.sub":       "Detect domain for routing",
            "set.fakeip":          "Fake-IP",
            "set.fakeip.sub":      "Faster resolving, fewer leaks",
            "set.mux":             "Enable Mux",
            "set.mux.sub":         "Multiple streams in one connection",
            "set.muxproto":        "Protocol",
            "set.routeprofile":    "Route profile",
            "set.routefinal":      "Final outbound",
            "set.routefinal.sub":  "Where traffic goes if no rule matched",
            "set.routelan":        "LAN bypass",
            "set.routelan.sub":    "LAN and private subnets — direct",
            "set.routeru":         "Direct access to RU sites",
            "set.routeru.sub":     "geosite:ru / geoip:ru bypass proxy",
            "set.adblock":         "Ad blocking",
            "set.adblock.sub":     "Block ad and tracker domains",
            "set.proxyall":        "Proxy everything",
            "set.proxyall.sub":    "Ignore bypasses (except LAN)",
            "set.checkup":         "Check for updates",
            "set.checkup.sub":     "Request sing-box GitHub releases · auto on start",
            "set.autoupdate":      "Auto-update",

            "label.lang":          "Interface language",

            "logs.title":   "Core logs",
            "logs.sub":     "For diagnostics · hidden by default",
            "logs.footer":  "Opens only from here — hidden in the main UI",
            "logs.filter":  "Search in log…",
            "logs.found":   "Lines matched:",

            "modal.profile.title":  "New profile",
            "modal.profile.hint":   "Will be created as a copy of current routing settings and rules. After creation it can be edited — changes are auto-saved.",
            "modal.profile.ph":     "e.g. Gaming / Only Discord / Stream",

            "modal.sub.title":      "New subscription",
            "modal.sub.url":        "SUBSCRIPTION LINK",
            "modal.sub.urlph":      "https://…  or  vless:// / vmess://",
            "modal.sub.name":       "NAME",
            "modal.sub.nameph":     "e.g. My VPN",

            "modal.rule.title":     "New rule",
            "modal.rule.type":      "TYPE",
            "modal.rule.value":     "VALUE",
            "modal.rule.action":    "ACTION",
            "modal.rule.ph":        "e.g. *.example.com  /  RU  /  app.exe",

            "modal.imp.title":      "Import rules",
            "modal.imp.hint":       "Paste config or rules array. Auto-detects format:\n• sing-box JSON (full config, object with route.rules, or rules array)\n• Clash / clash.meta YAML (rules: section)",

            "modal.srv.titlenew":   "New server",
            "modal.srv.title":      "Server",
            "modal.srv.name":       "NAME / LABEL",
            "modal.srv.nameph":     "e.g. Netherlands #1",
            "modal.srv.proto":      "PROTOCOL",
            "modal.srv.addrport":   "ADDRESS AND PORT",
            "modal.srv.uuidph":     "xxxxxxxx-xxxx-xxxx-…",
            "modal.srv.password":   "PASSWORD",
            "modal.srv.passwordph": "password",
            "modal.srv.method":     "ENCRYPTION METHOD",
            "modal.srv.security":   "SECURITY",
            "modal.srv.transport":  "TRANSPORT",
            "modal.srv.wgkey":      "PRIVATE KEY",
            "modal.srv.psk":        "PRE-SHARED KEY (opt.)",
            "modal.srv.pskph":      "base64 psk (if any)",

            "modal.share.title":    "Share server",
            "modal.share.noqr":     "QR not available",

            "loc.search":           "Search servers",
            "loc.empty":            "Nothing here yet",
            "loc.emptyhint":        "Paste a link from clipboard or add server manually",
            "loc.updated":          "Updated: ",
            "loc.fromsub":          "Some settings come from subscription «",

            "apps.search":          "Search app…",
            "apps.scanning":        "Scanning installed apps…",
            "apps.notfound":        "Nothing found for «",
            "apps.notfoundtail":    "»",

            "ctx.connect":          "Connect",
            "ctx.edit":             "Edit",
            "ctx.duplicate":        "Duplicate",
            "ctx.copylink":         "Copy link",
            "ctx.share":            "Share",
            "ctx.delete":           "Delete",

            "misc.profile.hint":    "A profile is a «snapshot» of all routing settings (LAN bypass, region, ads, final action, rules). Any edit is saved to the active profile automatically.",
            "misc.soon":            "soon",
            "misc.demoerr":         "show example error",

            "seg.auto":             "Auto",
            "seg.proxy":            "Proxy",
            "seg.direct":           "Direct",
            "seg.block":            "Block",
            "seg.vpn":              "VPN",
            "seg.last":             "Last",
            "seg.fastest":          "Fastest",
            "seg.global":           "Global",
            "seg.ru":               "RU",
            "seg.manual":           "Manual",

            "loc.searchph":         "Search servers",
            "loc.unsecured":        "Connection not protected",
            "loc.myip":             "My IP · ",
            "vrf.idle":             "Verify",
            "vrf.checking":         "Checking…",
            "vrf.match":            "VPN active",
            "vrf.mismatch":         "Wrong country",
            "vrf.off":              "VPN not working",
            "vrf.error":            "Verification failed",
            "loc.notfound":         "Nothing found",
            "loc.notfoundq":        "For query «",
            "loc.notfoundtail":     "» nothing found",
            "loc.fav.add":          "Add to favorites",
            "loc.fav.remove":       "Remove from favorites",

            "sub.loading":          "Loading…",
            "sub.applied":          "Settings applied from subscription «",
            "sub.notinstalled":     "not installed",
            "sub.update":           "Update",
            "misc.available":       "available",

            "apps.activeprofile":   "Active profile: «",
            "apps.defaultis":       "» (default: ",
            "apps.action.hint":     "Auto — action by profile. VPN — into tunnel. Direct — bypass tunnel.",

            "confirm.delsub":       "Delete subscription «",
            "confirm.delprof":      "Delete profile «",
            "confirm.delsrv":       "Delete server «",
            "confirm.tail":         "»?",
            "confirm.delperapp":    "Remove ALL per-app rules?",

            "misc.bigfox":          "🦊 Kitsune theme enabled",
            "misc.normalth":        "Normal theme",
            "misc.standard":        "Standard",
            "misc.newsrv":          "New server",
            "misc.savebtn":         "Save",
            "misc.addbtn":          "Add",
            "misc.langname.ru":     "Russian",
            "misc.langname.en":     "English",
            "misc.langnames":       "Russian / English",
            "misc.langnames.en":    "English / Russian",
            "units.mb":             " MB",
            "units.gb":             " GB"
        }
    })
}
